### PR TITLE
Remove memoization for increased flexibility; fixes #5

### LINKED ISSUE #5: Possible not to memoize top offset?
Plugin currently memoizes element's top offset the first time it needs it. In `topOffset()`:
```
    // We only want to calculate the vertical offset of the DOM element once,
    // both to be more efficient and because when the dropdown is rendered
    // upward we are changing its offset the first time we adjust its height.
    if (typeof $select2Results.data(OFFSET_KEY) === "undefined") {
      $select2Results.data(OFFSET_KEY, $select2Results.offset().top);
    }
```
Now, I have a select2 within a floating modal window. There, it's not rare for the user to move the window between one select2:open event and the next one. That makes memoized top offset obsolete, and consequent optimal height calculation wrong.

I tried to remove enclosing if, to always calculate the value, but then, I have wrong behaviour when rendering upwards. The comment above mentions something about this, but I'm not sure about which the correct fix would be. 

Any indication about how to proceed, please?

### PR DESCRIPTION
**Pull request by JacobEvelyn**
This PR resolves #5. I'll wait for the OP of that thread to confirm that this change fixes his issue before merging.

Assigning to @honigc to review in the meantime.

### CODE REVIEW

**Comment by honigc** [comment]
The proposed patch looks acceptable to me.

File: maximize-select2-height.js [hunk 1]
```diff
@@ -67,16 +51,45 @@
...
     var height;
-    var pixelsAboveDropdown = topOffset($select2Results) - $window.scrollTop();
+    var resultsBoxMiscellaniaHeight;
+    var widgetBoxOffset;
 
     if (dropdownDownwards) {
+      // When the dropdown appears downwards, the formula is:
+      //   total window size
+      // - size of content above results box
+      // - out-of-window pixels we've scrolled past
```
Comment (elmart) [inline maximize-select2-height.js]: This should be `+ out-of-window pixels`.
Or add parentheses after first minus, this is, `- (size of content above - out-of-window pixels)`.

File: maximize-select2-height.js [hunk 2]
```diff
@@ -67,16 +51,45 @@
...
+      // ------------------------------------------
+      //   total height available to us
+
       // innerHeight is more accurate across browsers than $(window).height().
-      height = window.innerHeight - pixelsAboveDropdown;
+      height = window.innerHeight -
+               $select2Results.offset().top -
```
Comment (elmart) [inline maximize-select2-height.js]: Same. Trailing `-` should be `+`.
Or add parens before `$select2Results.offset().top - ...`
